# Generated by Django 4.2.6 on 2023-10-20 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
