# Generated by Django 4.2.6 on 2023-10-20 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0004_alter_telegramuser_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramUser',
        ),
    ]
