# Generated by Django 4.2.6 on 2023-10-20 05:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('robot', '0005_delete_telegramuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='full_name')),
                ('user_id', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='user_id')),
            ],
        ),
    ]
