# Generated by Django 4.2.6 on 2023-10-20 05:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='user_id',
            field=models.BigIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='user_id'),
        ),
    ]
